### ISSUE TITLE
Discord rich presence not working

### ISSUE THREAD

**Issue by SomeoneFamous69** [MRKDaGods/BetterAnghami#1]
@MRKDaGods
sorry to bother you, but i didnt see any sort of tutorial/documentation about the discord rich presence you added, so please can you write how to add the app to discord's rich presence?

**Comment by MRKDaGods** [comment]
Hey there, Discord RPC should be running by default.

**Comment by SomeoneFamous69** [comment]
no need to add it to discord?

**Comment by MRKDaGods** [comment]
Nope, just run Better Anghami and everything should work!
